#ifndef MODELS_SERVER_STATUS_H
#define MODELS_SERVER_STATUS_H

#include <QQuickItem>
#include <nlohmann/json.hpp>

namespace Models {
    enum DATA_BASE_EXECUTION_STATUS {
        //Global part
        DATA_BASE_COMPLETED_SUCCESSFULY,
        DATA_BASE_FAILED,

        //Profile part
        DATA_BASE_PROFILE_WITH_SUCH_LOGIN_IS_ALREADY_EXIST,
        DATA_BASE_PROFILE_WITH_SUCH_NAME_IS_ALREADY_EXIST,
        DATA_BASE_THERE_IS_NO_PROFILE_WITH_SUCH_NAME,
        DATA_BASE_THERE_IS_NO_PROFILE_WITH_SUCH_ID,
        DATA_BASE_THERE_IS_NO_PROFILE_WITH_SUCH_LOGIN_AND_PASSWORD,
        DATA_BASE_THERE_IS_NO_CONFIG_WITH_SUCH_PROFILE_ID,
        DATA_BASE_UNKNOWN_PROFILE,

        //Room part
        DATA_BASE_ROOM_CREATION_FAILED,
        DATA_BASE_THERE_IS_NO_ROOM_WITH_SUCH_PARAMETERS,
        DATA_BASE_ROOM_WITH_SUCH_PARAMETERS_IS_ALREADY_EXIST,
        DATA_BASE_THIS_PROFILE_IS_ALREADY_EXIST_IN_THIS_ROOM,
        DATA_BASE_ROOM_ACCESS_ERROR,

        //Task part
        DATA_BASE_TASK_CREATION_FAILED,
        DATA_BASE_THERE_IS_NO_TASK_WITH_SUCH_PARAMETERS,
        DATA_BASE_TASK_WITH_SUCH_PARAMETERS_IS_ALREADY_EXIST,
        DATA_BASE_THIS_PROFILE_IS_ALREADY_ASSIGNEE_TO_THIS_TASK,
        DATA_BASE_THIS_ID_IS_NOT_ASSIGNEE_THIS_TASK,
        DATA_BASE_THIS_PROFILE_IS_ALREADY_REVIEW_THIS_TASK,
        DATA_BASE_THIS_ID_IS_NOT_REVIEW_THIS_TASK,

        //Join part
    };
    enum JWT_EXECUTION_STATUS {
        JWT_COMPLETED_SUCCESSFULY,
        JWT_DECODING_FILED,
        JWT_NO_TOKEN_HEADER,
        JWT_TIME_LIMIT_EXECEEDED,
        JWT_CREATION_FAILED,
    };
    enum FILE_PARSER_EXECUTION_STATUS {
        FILE_PARSER_COMPLETED_SUCCESSFULY,
        FILE_PARSER_FAILED,

        FILE_PARSER_FILE_NOT_FOUND,
        FILE_PARSER_READING_DATA_ERROR,
        FILE_PARSER_WRITING_DATA_ERROR,
    };

    constexpr size_t DATA_BASE_BITS_COUNT{6};
    constexpr size_t JWT_BITS_COUNT{3};
    constexpr size_t FILE_PARSER_BITS_COUNT{3};

    struct ServerStatus {
        int status;
        DATA_BASE_EXECUTION_STATUS data_base_status;
        JWT_EXECUTION_STATUS JWT_status;
        FILE_PARSER_EXECUTION_STATUS file_parse_status;

        ServerStatus(int status);
    private:
        int applyMask(int number, int bitCount, int bitShift);
    };
}

#endif // MODELS_SERVER_STATUS_H
